# non-ratelimitied 1byte echo rpc-perf config
#
# use-case: measure the peak echo rate for a single connection with minimal payload

[general]
threads = 2
connections = 1000
duration = 5
windows = 10
protocol = "echo"
tcp-nodelay = false
ipv4 = true
ipv6 = true

[[workload]]
name = "echo"
method = "echo"
rate = 0

[[workload.parameter]]
style = "static"
size = 1
seed = 0
